# Generated by Django 5.2.5 on 2025-08-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('answers', models.JSONField()),
                ('attempted_count', models.IntegerField()),
                ('unattempted_count', models.IntegerField()),
                ('total_time_taken', models.IntegerField(help_text='Time in seconds')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
